### ISSUE TITLE
sqlite3 missing

### ISSUE THREAD

**Issue by b1rger** [macadmins/puppet-macauthdb#3]
hi,

i'm trying to use the macauthdb module on high sierra. when i run puppet agent, i get
`Error: Could not find a suitable provider for macauthdb`
and with debug messages i get multiple:
```
Debug: Failed to load library 'sqlite3' for feature 'sqlite'
Debug: Puppet::Type::Macauthdb::ProviderDefault: feature sqlite is missing
```
although sqlite is installed:
```
sudo gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
CFPropertyList (2.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
libxml-ruby (2.9.0)
minitest (5.8.5)
net-telnet (0.1.1)
nokogiri (1.5.6)
power_assert (0.2.6)
psych (2.1.0)
rake (10.4.2)
rdoc (4.2.1)
sqlite3 (1.3.11)
test-unit (3.1.5)
```
do you have any idea how to fix this?

**Comment by grahamgilbert** [comment]
Puppet doesn't use the system ruby. I assume it needs to be installed using puppet's own gem.

**Comment by clburlison** [comment]
This module should install the required gems per https://github.com/macadmins/puppet-macauthdb/blob/master/manifests/install.pp#L6

as long as your set `$macauthdb::params::install_gems,` to `true` in your hiera config.

Cheers

**Comment by grahamgilbert** [comment]
Thanks Clayton, closing.
