### ISSUE TITLE
User cannot login machine if crypt is not installed correctly with modified auth.db

### ISSUE THREAD

**Issue by nieivan** [macadmins/puppet-macauthdb#4]
the logic of puppet-crypt module is to modify auth.db first, then install crypt client. In some cases, machines auth.db have been modified, but download and install crypt failed, which causes the user can't login because of no crypt installed.

**Comment by nieivan** [comment]
Is it possible to change the logic? install crypt first, then configure auth.db?

**Comment by grahamgilbert** [comment]
Yes it’s possible, but has nothing to do with this module. You want to look at https://github.com/airbnb/puppet-crypt
